SpringFarmer/SpringFarmer

src/main/resources/application.properties
=> [김민혁] properties 테스트

src/main/java/com/codefarm/farmer/FarmerApplication.java, src/main/resources/application.properties, src/main/resources/config/config.xml, src/main/resources/templates/program/list.html
김지연 초기설정(서버연결, config, templates)
=> 221110 김지연 초기설정(서버연결, config, templates)

pom.xml
박수현
2022.11.10 11:12
라이브서버 라이브러리 추가
=> 박수현 라이브서버 라이브러리 추가

src/main/java/com/codefarm/farmer/controller/MyPageController.java, src/main/resources/static/css/myPage/myPage.css, src/main/resources/templates/myPage/setting.html
박수현
2022.11.10 17:29
Controller 패키지, 파일 추가
=> 박수현 Controller 패키지, 파일 추가

src/main/resources/static/css/common/font.css, src/main/resources/static/css/myPage/myPage.css, src/main/resources/templates/myPage/setting.html
박수현
2022.11.10.19:20
font.css 파일 추가
=> 박수현 font.css 파일 추가

src/main/resources/static/css/myPage/myPage.css, src/main/resources/templates/myPage/setting.html
박수현
2022.11.11 01:17
마이페이지 메인 작업 중
=> 박수현 마이페이지 메인 작업 중

pom.xml, src/main/java/com/codefarm/farmer/controller/MentroController.java, src/main/resources/static/css/mentor/mentorIntro.css, src/main/resources/templates/mentor/mentorIntro.html, src/main/resources/templates/program/list.html
멘토main(program/list 잘못 작성한 부분 삭제)
=> 멘토main(program/list 잘못 작성한 부분 삭제)

src/main/resources/static/css/main/main.css, src/main/resources/templates/main/main.html
=> 11.13 [김민혁] 메인 페이지 수정본

src/main/resources/static/css/footer/footer.css, src/main/resources/static/css/information/policy.css, src/main/resources/static/css/inquire/inquire.css, src/main/resources/static/css/main/main.css, src/main/resources/templates/information/policy.html, src/main/resources/templates/inquire/writeInquire.html
=> 11.13 [김민혁] 헤더, 푸터 긴급치료

src/main/resources/static/css/information/readyTest.css, src/main/resources/static/css/information/stepTest.css, src/main/resources/static/css/inquire/inquire.css, src/main/resources/templates/information/cropInformation.html, src/main/resources/templates/information/policy.html, src/main/resources/templates/information/readyTest.html, src/main/resources/templates/information/stepTest.html, src/main/resources/templates/inquire/writeInquire.html
서승우
2022.11.13
지원정책, 작물정보, 테스트, 문의하기 (1차완료 및 헤더,푸터 추가완료)
=> 지원정책, 작물정보, 테스트, 문의하기 (1차완료 및 헤더,푸터 추가완료)

src/main/java/com/codefarm/farmer/controller/MentorController.java, src/main/resources/static/css/mentor/mentorIntro.css, src/main/resources/static/css/mentor/mentorList.css, src/main/resources/templates/mentor/mentorIntro.html, src/main/resources/templates/mentor/mentorList.html
=> 멘토 소개, 멘토 목록 페이지 1차

src/main/java/com/codefarm/farmer/controller/AdminBoardController.java, src/main/resources/static/css/adminBoard/board.css, src/main/resources/static/css/adminCommon/contents.css, src/main/resources/static/css/adminCommon/side_menu.css, src/main/resources/static/css/adminNotice/notice.css, src/main/resources/static/css/adminNotice/noticeWrite.css, src/main/resources/static/css/adminProgram/program_participant.css, src/main/resources/static/css/adminReply/reply.css, src/main/resources/static/css/adminUser/user.css, src/main/resources/static/js/adminCommon/check.js, src/main/resources/templates/adminAsk/ask_write.html, src/main/resources/templates/adminBoard/board.html, src/main/resources/templates/adminNotice/notice_write.html
=> 20221113 연태관 관리자 페이지 작업중

src/main/resources/static/css/information/policy.css, src/main/resources/static/css/information/readyTest.css, src/main/resources/static/css/information/stepTest.css, src/main/resources/static/css/inquire/inquire.css, src/main/resources/templates/information/cropInformation.html, src/main/resources/templates/information/policy.html, src/main/resources/templates/information/readyTest.html, src/main/resources/templates/information/stepTest.html, src/main/resources/templates/inquire/writeInquire.html
서승우
2022.11.14 
information, inquire 배너 수정
=> information, inquire 배너 수정

src/main/java/com/codefarm/farmer/controller/MentorController.java, src/main/resources/static/css/mentor/mentorDetail.css, src/main/resources/static/css/mentor/mentorIntro.css, src/main/resources/static/css/mentor/mentorList.css, src/main/resources/templates/mentor/mentorDetail.html, src/main/resources/templates/mentor/mentorIntro.html
=> 멘토 메인 배너 1개 / 멘토 상세페이지 처음부분

src/main/resources/static/css/program/apply.css, src/main/resources/static/css/program/pay.css, src/main/resources/static/css/program/register.css, src/main/resources/static/js/program/apply.js, src/main/resources/static/js/program/pay.js, src/main/resources/static/js/program/register.js, src/main/resources/templates/program/apply.html, src/main/resources/templates/program/detail.html, src/main/resources/templates/program/pay.html, src/main/resources/templates/program/register.html
=> 221117 김지연 프로그램 등록 페이지 작업 중

src/main/resources/static/css/alba/detail.css, src/main/resources/templates/alba/detail.html, src/main/resources/templates/alba/list.html, src/main/resources/templates/header/header.html
아르바이트 목록 페이지 벤치마킹 사이트 찾기 및 상세 페이지 일부 작업 진행
=> 11.17(목) [김민혁] 아르바이트 목록 페이지 벤치마킹 사이트 찾기 및 상세 페이지 일부 작업 진행

src/main/java/com/codefarm/farmer/controller/admin/AdminBannerController.java, src/main/java/com/codefarm/farmer/controller/admin/AdminCropInformationController.java, src/main/java/com/codefarm/farmer/controller/admin/AdminNoticeController.java, src/main/java/com/codefarm/farmer/controller/admin/AdminPolicyController.java, src/main/resources/static/css/admin/adminNotice/noticeWrite.css, src/main/resources/templates/adminAsk/ask.html, src/main/resources/templates/adminAsk/ask_write.html, src/main/resources/templates/adminBanner/banner.html, src/main/resources/templates/adminBanner/banner_write.html, src/main/resources/templates/adminBoard/board.html, src/main/resources/templates/adminCropInformation/cropInformation_update.html, src/main/resources/templates/adminJob/job.html, src/main/resources/templates/adminMentor/promotion.html, src/main/resources/templates/adminNotice/notice.html, src/main/resources/templates/adminNotice/notice_update.html, src/main/resources/templates/adminNotice/notice_write.html, src/main/resources/templates/adminPolicy/policy.html, src/main/resources/templates/adminPolicy/policy_update.html, src/main/resources/templates/adminPolicy/policy_write.html, src/main/resources/templates/adminProgram/program_list.html, src/main/resources/templates/adminProgram/program_participant.html, src/main/resources/templates/adminReply/board_reply.html, src/main/resources/templates/adminReply/mentor_reply.html, src/main/resources/templates/fix/side_menu.html
=> 20221116 연태관 / 글 수정 페이지 작업 완료

project.code-workspace, src/main/java/com/codefarm/farmer/controller/MentorController.java, src/main/resources/static/css/mentor/mentorDetail.css, src/main/resources/static/css/mentor/mentorWrite.css, src/main/resources/templates/mentor/mentorDetail.html, src/main/resources/templates/mentor/mentorIntro.html, src/main/resources/templates/mentor/mentorWrite.html
호석 멘토 상세페이지, 멘토 홍보그 작성 페이지 작성중..
=> 호석 멘토 상세페이지, 멘토 홍보그 작성 페이지 작성중..

src/main/resources/static/css/mento/chatting.css, src/main/resources/static/css/mento/detail.css, src/main/resources/static/css/mento/intro.css, src/main/resources/static/css/mento/write.css, src/main/resources/static/js/mento/write.js, src/main/resources/templates/mento/chatting.html, src/main/resources/templates/mento/detail.html, src/main/resources/templates/mento/intro.html, src/main/resources/templates/mento/list.html, src/main/resources/templates/mento/write.html
=> 호석 전체적으로 퍼블리싱 틀 완료

src/main/resources/static/css/community/register.css, src/main/resources/static/js/community/register.js, src/main/resources/templates/community/register.html, src/main/resources/templates/header/header.html, src/main/resources/templates/myPage/setting.html
박수현
2022.11.21 17:34
커뮤니티 작성 작업 중
헤더 수정
=> 박수현 커뮤니티 작성 작업 중, 헤더 수정

src/main/resources/static/css/mento/chatting.css, src/main/resources/static/css/mento/intro.css, src/main/resources/static/css/mento/list.css, src/main/resources/static/css/mento/write.css, src/main/resources/static/js/mento/write.js, src/main/resources/templates/mento/detail.html, src/main/resources/templates/mento/intro.html, src/main/resources/templates/mento/list.html, src/main/resources/templates/mento/write.html
=> 호석 11/21 수업 끝나기 전 푸시

src/main/java/com/codefarm/farmer/controller/admin/AdminBannerController.java, src/main/resources/static/js/admin/adminCommon/check.js, src/main/resources/templates/adminAsk/ask-detail.html, src/main/resources/templates/adminBanner/banner-update.html, src/main/resources/templates/adminBanner/banner-write.html, src/main/resources/templates/adminBanner/banner.html, src/main/resources/templates/adminBoard/board.html, src/main/resources/templates/adminCropInformation/cropInformation-update.html, src/main/resources/templates/adminCropInformation/cropInformation-write.html, src/main/resources/templates/adminCropInformation/cropInformation.html, src/main/resources/templates/adminJob/job.html, src/main/resources/templates/adminMentor/promotion.html, src/main/resources/templates/adminNotice/notice-update.html, src/main/resources/templates/adminNotice/notice-write.html, src/main/resources/templates/adminNotice/notice.html, src/main/resources/templates/adminPolicy/policy-update.html, src/main/resources/templates/adminPolicy/policy-write.html, src/main/resources/templates/adminPolicy/policy.html, src/main/resources/templates/adminProgram/program-list.html
20221122 연태관 / 첨부파일 미리보기 js랑 멘토관리 페이지만 만들면 끝
=> 20221122 연태관 / 첨부파일 미리보기 js랑 멘토관리 페이지만 만들면 끝

src/main/resources/static/css/mento/detail.css, src/main/resources/static/css/mento/list.css, src/main/resources/static/css/mento/write.css, src/main/resources/static/js/mento/detail.js, src/main/resources/static/js/mento/list.js, src/main/resources/templates/mento/detail.html, src/main/resources/templates/mento/list.html, src/main/resources/templates/mento/write.html
=> 호석 write 모달창 전 까지 js 추가

src/main/resources/static/css/program/detail.css, src/main/resources/static/css/program/list.css, src/main/resources/static/css/program/register.css, src/main/resources/static/js/program/list.js, src/main/resources/static/js/program/register.js, src/main/resources/templates/program/applyOk.html, src/main/resources/templates/program/detail.html, src/main/resources/templates/program/register.html
=> 221122 김지연 프로그램 작업 완료!

src/main/resources/static/css/mento/write.css, src/main/resources/static/js/mento/write.js, src/main/resources/templates/mento/write.html
=> write 화살표 추가

src/main/resources/static/css/mento/write.css, src/main/resources/static/js/mento/write.js, src/main/resources/templates/mento/write.html
호석 write 썸머노트, 유효성 검사 처리 ,첨부파일 넣으면 이미지 등록되는거 진행중
=> 호석 write 썸머노트, 유효성 검사 처리 ,첨부파일 넣으면 이미지 등록되는거 진행중

src/main/resources/templates/adminAsk/ask.html, src/main/resources/templates/adminBoard/board.html, src/main/resources/templates/adminJob/job-participant.html, src/main/resources/templates/adminJob/job.html, src/main/resources/templates/adminMentor/mentor.html, src/main/resources/templates/adminMentor/promotion.html, src/main/resources/templates/adminNotice/notice-update.html, src/main/resources/templates/adminNotice/notice-write.html, src/main/resources/templates/adminNotice/notice.html, src/main/resources/templates/adminPolicy/policy.html, src/main/resources/templates/adminProgram/program-list.html, src/main/resources/templates/adminProgram/program-participant.html, src/main/resources/templates/adminUser/user.html, src/main/resources/templates/fix/side_menu.html
=> 20221123 연태관 관리자페이지 다시 수정

src/main/resources/static/css/information/readyTest.css, src/main/resources/static/css/information/stepTest.css, src/main/resources/templates/information/readyTest.html, src/main/resources/templates/information/stepTest.html, src/main/resources/templates/program/detail.html, src/main/resources/templates/program/register.html
221123 김지연/test글자 변경/program 수정
=> 221123 김지연/test글자 변경/program 수정

src/main/resources/static/css/mento/write.css, src/main/resources/static/js/mento/write.js, src/main/resources/templates/mento/detail.html, src/main/resources/templates/mento/write.html
=> 호석 멘토 수정버전

src/main/resources/static/css/mento/chatting.css, src/main/resources/static/css/mento/write.css, src/main/resources/static/js/mento/detail.js, src/main/resources/static/js/mento/write.js, src/main/resources/templates/mento/chatting.html, src/main/resources/templates/mento/detail.html, src/main/resources/templates/mento/write.html
=> 호석 멘토 수정중 거의 완료

src/main/resources/static/css/myPage/paging.css, src/main/resources/static/css/myPage/sideMenu.css, src/main/resources/templates/myPage/mentoring.html, src/main/resources/templates/myPage/program.html
박수현
2022.11.25 10:44
오타 수정
페이징 수정 완료
=> 박수현 오타 수정, 페이징 수정 완료

src/main/resources/static/css/admin/adminCommon/contents.css, src/main/resources/static/css/admin/adminCommon/form.css, src/main/resources/static/css/admin/adminCommon/sideMenuList.css, src/main/resources/static/css/admin/adminCommon/side_menu.css, src/main/resources/static/css/admin/adminMain/main_contents.css, src/main/resources/static/css/admin/adminNotice/noticeForm.css, src/main/resources/static/css/admin/adminPolicy/policy.css, src/main/resources/static/css/admin/adminProgram/program_participant.css, src/main/resources/templates/fix/side_menu.html
=> 20221125 연태관 / 관리자 페이지 진짜진짜 끝

src/main/resources/static/css/alba/detail.css, src/main/resources/static/js/alba/detail.js, src/main/resources/static/js/alba/write.js, src/main/resources/templates/alba/detail.html, src/main/resources/templates/alba/write.html, src/main/resources/templates/main/main.html
메인 페이지 FAQ 문구 수정
아르바이트 페이지 : 지원취소, 삭제하기 버튼 클릭 시 모달창 나옴. 수정하기 버튼 클릭시 write페이지로 이동
=> 메인, 아르바이트 페이지 토요일 피드백 반영

src/main/java/com/codefarm/farmer/controller/community/CommunityController.java, src/main/java/com/codefarm/farmer/controller/myPage/MyPageController.java, src/main/java/com/codefarm/farmer/controller/notice/NoticeController.java
박수현
2022.11.27 21:12
컨트롤러 경로 수정
=> 박수현 컨트롤러 경로 수정

src/main/resources/static/css/mento/chatting.css, src/main/resources/static/css/mento/detail.css, src/main/resources/static/css/mento/intro.css, src/main/resources/static/css/mento/list.css, src/main/resources/static/css/mento/write.css, src/main/resources/static/js/mento/chatting.js, src/main/resources/static/js/mento/detail.js, src/main/resources/static/js/mento/write.js, src/main/resources/templates/mento/chatting.html, src/main/resources/templates/mento/detail.html, src/main/resources/templates/mento/intro.html, src/main/resources/templates/mento/write.html
=> 호석 첨부파일 제외 완료?..

src/main/resources/static/css/admin/main_contents.css, src/main/resources/templates/admin/banner-update.html, src/main/resources/templates/admin/banner-write.html, src/main/resources/templates/admin/banner.html, src/main/resources/templates/admin/main.html
=> 20221127 연태관 / 관리자페이지 수정
